[package]
name = "starsoup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
env_logger = "0.10.0"
gumdrop = "0.8.1"
rpassword = "7.2.0"
noshell = { path = "../noshell" }
